### ISSUE TITLE
项目开发约定

### ISSUE THREAD

**Issue by okbug** [okbug/college-design#4]
Merge使用 `rebase` 的方式
分支命名以 `feature` 的形式进行Merge

2022-02-14 - 计划：

主应用向TS迁移

开发 `docute` 子应用

添加 husky 以及 perttier 相关的

单一大仓的实践

**Comment by okbug** [comment]
所有的PR(我自己提交的) 都(我自己)CR之后再合入主干

**Comment by okbug** [comment]
# 项目架构
主应用：`main-app`
自己通过webpack5构建的，目前还是JS项目

子应用：`docute`
文档子应用：CRA 构建
React@17  + TypeScript + React-Router-Dom@6 搭建
使用 customize-cra  重写 webpack 配置

子应用: `PPTist` (ppturbo)
演示文稿子应用：VueCli4构建
Vue3 + script setup + TypeSctipt + Vue-Router@4 + Pinia

**Comment by okbug** [comment]
仓库管理准备到时候加上 gitsubmodule  或者 lerna(turboRepo)类的 Monorepo 管理

**Comment by WindRunnerMax** [comment]
好
